summa-tx/bitcoin-spv

contracts/SPVStore.sol

bubble not ubble

---

README.md
golang/README.md
solidity/README.md

chore: tweak all readmes

---

golang/btcspv/types.go
golang/btcspv/types_test.go
golang/btcspv/utils.go
golang/btcspv/utils_test.go

More fixes to json marshalling and refactoring how addresses work

Address error fixes and ser/deser fixes

---

golang/cli/vout.go

added address in prettifyOutput

---

golang/btcspv/bitcoin_spv.go
golang/btcspv/bitcoin_spv_test.go
golang/btcspv/types.go
golang/btcspv/types_test.go
golang/btcspv/utils.go
golang/btcspv/utils_test.go
golang/btcspv/validate_spv.go
golang/btcspv/validate_spv_test.go

We defined types for RawHeader and Hash256Digest. This PR adds them to all relevant functions

Golang type refactor

---

golang/cli/header.go
golang/cli/prove.go
golang/cli/spvcli.go
golang/cli/vin.go
golang/cli/vout.go

Update go cli with new types

---

golang/btcspv/bitcoin_spv.go
golang/btcspv/bitcoin_spv_test.go
golang/btcspv/validate_spv_test.go

Remove hex dependency in btcutils

---

solidity/contracts/BTCUtils.sol
solidity/contracts/BytesLib.sol
solidity/contracts/ValidateSPV.sol
solidity/contracts/ValidateSPVDelegate.sol
solidity/contracts/test/ValdiateSPVTest.sol
solidity/test/ValidateSPV.test.js

Added some transactions to tests to enable `eth-gas-reporter` to collect something.
Before:
```
····················|·························|·············|·············|·············|··············|
|  Contract         ·  Method                 ·  Min        ·  Max        ·  Avg        ·  # calls     ·
····················|·························|·············|·············|·············|··············|
|  ValidateSPVTest  ·  parseInputTx           ·      37515  ·      41205  ·      39886  ·           5  ·
····················|·························|·············|·············|·············|··············|
|  ValidateSPVTest  ·  parseOutputTx          ·      29471  ·      30602  ·      30234  ·           9  ·
····················|·························|·············|············· …
```

Optimized gas a bit

---

solidity/contracts/BTCUtils.sol

Refactored hash256

---

golang/btcspv/bitcoin_spv.go
golang/btcspv/bitcoin_spv_test.go
golang/btcspv/bitcoin_spv_test_types.go
golang/btcspv/types.go
golang/btcspv/utils_test.go
golang/btcspv/utils_test_types.go
golang/btcspv/validate_spv_test.go
golang/btcspv/validate_spv_test_types.go
testVectors.json

Updates Golang tests to use strongly typed cases instead of messy type assertions.

Overhaul golang testing

---

golang/btcspv/bitcoin_spv.go
golang/btcspv/test_utils/bitcoin_spv_test_types.go
golang/btcspv/test_utils/validate_spv_test_types.go
js/src/ValidateSPV.js
js/src/index.js
js/src/sighash.js
js/test/BTCUtils.test.js
js/test/ValidateSPV.test.js
js/test/utils.test.js
rust/src/utils.rs
testVectors.json

- Adds docs to `sighash.js`
- Updates documentation in `ValidateSPV.js`, using typedefs is so much cleaner

Sighash docs

---

js/clients/README.md
js/clients/lib/BcoinClient.js
js/clients/package-lock.json
js/clients/package.json
js/clients/test/BcoinClient-test.js

Closes #146 
- No tests written for this yet, going to make issue.

removed be/le from js client, fixed testing setup

---

solidity/contracts/BTCUtils.sol

Docs and some comments for validateVout were copied from validateVin

Fixes wrong docs/comments for validateVout

---

solidity/contracts/TypedMemView.sol
solidity/contracts/ViewSPV.sol
solidity/contracts/test/ViewSPVtest.sol

- Moves type conversions and validations to `ViewSPVtest.sol`
- Adds type assertions to `ViewSPV.sol`.

View spv type assertions

---

c/csrc/btcspv.c
c/csrc/check_btcspv.c
golang/btcspv/bitcoin_spv.go
golang/btcspv/bitcoin_spv_test.go
golang/btcspv/test_utils/bitcoin_spv_test_types.go
js/package.json
js/src/BTCUtils.js
js/test/BTCUtils.test.js
run_tests.sh
rust/Cargo.lock
rust/Cargo.toml
rust/src/btcspv.rs
rust/src/lib.rs
rust/src/types.rs
solidity/contracts/BTCUtils.sol
solidity/contracts/BTCUtilsDelegate.sol
solidity/contracts/test/BTCUtilsTest.sol
solidity/package.json
solidity/test/BTCUtils.test.js
testVectors.json

- add explicit length checks to extract hash to prevent unsafe usage
- remove extract script sig len

Extract hash bugfixes

---

solidity/contracts/ViewBTC.sol
solidity/contracts/test/TestMemView.sol

Adds an error message for non-minimal compact ints

Non-minimal Compact Int error

---

solidity/contracts/BTCUtils.sol
solidity/contracts/CheckBitcoinSigs.sol

May add some more if I find any, leaving it as a draft for now.

Adds some additional docs fixes

---

solidity/test/ViewSPV.test.js
testVectors.json

Jokes on you, now you get to review another PR (:

Test for `checkWork`

---

c/csrc/btcspv.c
c/csrc/btcspv.h
c/csrc/check_btcspv.c
c/csrc/evalspv.c
c/csrc/evalspv.h
c/csrc/swap-demo.c
testVectors.json

Adds several typed views to prevent accidental type confusion in C parsing. Includes #158

Better c types

---

js/clients/lib/index.js
js/package-lock.json

added block and tx vendors to `lib/index.js` export
am i doing this right?? did i do the thing?

Prepare npm publish
